apiVersion: v1
kind: Service
metadata:
  name: postgres-prod
  namespace: prod
  labels:
    app: postgres-prod
spec:
  ports:
  - port: 5432
    name: db
  selector:
    app: postgres-prod
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-prod
  namespace: prod
spec:
  serviceName: postgres-prod
  replicas: 1
  selector:
    matchLabels:
      app: postgres-prod
  template:
    metadata:
      labels:
        app: postgres-prod
    spec:
      containers:
        - name: postgres-prod
          image: postgres:13-alpine
          ports:
          - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-prod-pv
              mountPath: /usr/local/var/postgres
      volumes:
      - name: postgres-prod-pv
        persistentVolumeClaim:
          claimName: postgress-prod-pv-claim