apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-pv-claim
  namespace: stage
spec:
  storageClassName: stage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi