apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: stage
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: db
  clusterIP: None
  selector:
    app: postgres
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: stage
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          ports:
          - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-pv
              mountPath: /usr/local/var/postgres
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgress-pv-claim